name: SOUTENANCE
description: INFO SOUTENANCE
title: "[INfO SOUTENANCE]: "
labels: ["SOUTENANCE"]
projects: ["PROJET-2"]
assignees:
  - Quentin-M58
body:
  - type: markdown
    attributes:
      value: INFORMATION SOUTENANCE
  - type: input
    id: date
    attributes:
      label: DATE
      description: Date de la soutenance
      placeholder: exemple 02/02/2024 11h
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: description
      description: description
      placeholder: description
      value: "description"
    validations:
      required: true
